name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Spring Boot App
        run: docker build -t spring-boot-app -f api/Dockerfile .

      - name: Build Angular App
        run: docker build -t angular-app -f frontend/Dockerfile .

      - name: Run docker compose
        run: docker-compose up -d

      - name: Push Docker images to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag spring-boot-app $DOCKER_USERNAME/spring-boot-app:latest
          docker tag angular-app $DOCKER_USERNAME/angular-app:latest
          docker push $DOCKER_USERNAME/spring-boot-app:latest
          docker push $DOCKER_USERNAME/angular-app:latest

      - name: Deploy to Docker Compose
        run: docker-compose up -d