name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - frontend/**
      - .github/workflows/pipeline-frontend.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test --if-present

      - name: Build Angular app
        run: |
          npm run build --prod
        env:
          NG_APP_API_URL: ${{ secrets.API_URL }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/frontend:latest

  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    needs: [ build-image ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auth with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy my-angular-app \
          --image=${{ secrets.DOCKER_USERNAME }}/frontend:latest \
          --platform=managed \
          --region=europe-west3 \
          --allow-unauthenticated \
          --revision-suffix=$(date +%s) \
          --set-env-vars API_URL=${{ secrets.API_URL }}
